services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:patrick2004@db:5432/calendar?schema=public
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: patrick2004
      POSTGRES_DB: calendar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
