import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: "1rem", backgroundColor: "#111", color: "white" }}>
          <nav style={{ display: "flex", gap: "1rem" }}>
            <Link href="/" style={{ color: "white" }}>Home</Link>
            <Link href="/settings/2fa" style={{ color: "white" }}>Enable 2FA</Link>
            {/* add other links as needed */}
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
